apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-config-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  volumeName: sonarr-config-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-downloads-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  storageClassName: ""
  volumeName: sonarr-download-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-media-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
  storageClassName: ""
  volumeName: sonarr-media-pv
