apiVersion: v1
kind: PersistentVolume
metadata:
  name: prowlarr-config-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  nfs:
    server: truenas.billnet.local
    path: /mnt/nvme/Configs/prowlarr
