apiVersion: v1
kind: PersistentVolume
metadata:
  name: radar-config-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  nfs:
    server: truenas.billnet.local
    path: /mnt/nvme/Configs/radar
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: radar-media-pv
spec:
  capacity:
    storage: 1Ti
  accessModes:
  - ReadWriteMany
  nfs:
    server: truenas.billnet.local
    path: /mnt/rust/Data/media
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: radar-download-pv
spec:
  capacity:
    storage: 500Gi
  accessModes:
  - ReadWriteMany
  nfs:
    server: truenas.billnet.local
    path: /mnt/rust/Data/deluge
