apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-config-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  volumeName: radarr-config-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-downloads-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  storageClassName: ""
  volumeName: radarr-download-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-media-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
  storageClassName: ""
  volumeName: radarr-media-pv
