apiVersion: v1
kind: Service
metadata:
  name: forgejo-ssh
  annotations:
    metallb.universe.tf/allow-shared-ip: "homelab"
spec:
  selector:
    app: forgejo
  ports:
    - port: 2222
      targetPort: 2222
  type: LoadBalancer
