apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |
    providers:
      kubernetesGateway:
        enabled: true
    experimental:
      kubernetesGateway:
        enabled: true
    ports:
      websecure:
        port: 8443
        expose:
          default: true
        exposedPort: 443
        protocol: TCP
