apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bazarr-media-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Ti
  storageClassName: ""
  volumeName: bazarr-media-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bazarr-config-pvc
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
