apiVersion: v1
kind: PersistentVolume
metadata:
  name: bazarr-media-pv
spec:
  capacity:
    storage: 1Ti
  accessModes:
  - ReadWriteOnce
  nfs:
    server: truenas.billnet.local
    path: /mnt/rust/Data/media
