apiVersion: apps/v1
kind: Deployment
metadata:
  name: deluge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deluge
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: deluge
    spec:
      containers:
        - name: gluetun
          image: qmcgaw/gluetun
          securityContext: 
            capabilities:
              add:
                - NET_ADMIN
          ports:
            - containerPort: 8112
          env:
            - name: VPN_SERVICE_PROVIDER
              value: protonvpn
            - name: VPN_TYPE
              value: openvpn
            - name: OPENVPN_USER
              valueFrom:
                secretKeyRef:
                  name: gluetun-vpn-user
                  key: openvpn_user
            - name: OPENVPN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: gluetun-vpn-pass
                  key: openvpn_pass
            - name: SERVER_COUNTRIES
              value: United States
            - name: DOT
              value: "off"
            - name: DNS_ADDRESS
              value: "9.9.9.9"
            - name: DNS_KEEP_NAMESERVER
              value: "on"
          volumeMounts:
            - name: tun
              mountPath: /dev/net/tun
        - name: deluge
          #image: linuxserver/deluge:latest
          image: linuxserver/deluge:2.2.0-r1-ls364
          volumeMounts:
            - name: config
              mountPath: /config
            - name: data
              mountPath: /downloads
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "3000"
            - name: TZ
              value: America/Denver
      volumes:
        - name: tun
          hostPath:
            path: /dev/net/tun
            type: CharDevice
        - name: config
          persistentVolumeClaim:
            claimName: deluge-config-pvc
        - name: data
          persistentVolumeClaim:
            claimName: deluge-data-pvc
