apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: deluge-config-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  volumeName: deluge-config-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: deluge-data-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  storageClassName: ""
  volumeName: deluge-data-pv
