apiVersion: v1
kind: PersistentVolume
metadata:
  name: deluge-config-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  nfs:
    server: truenas.billnet.local
    path: /mnt/nvme/Configs/deluge
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: deluge-data-pv
spec:
  capacity:
    storage: 500Gi
  accessModes:
  - ReadWriteMany
  nfs:
    server: truenas.billnet.local
    path: /mnt/rust/Data/deluge
