apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-home-cert
  namespace: default
spec: 
  secretName: wildcard-home-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - "*.home.williamlhunter.com"
